### ISSUE TITLE
bcrypt_needs_rehash returns true even when the hash doesn't need rehashing

### ISSUE THREAD

**Issue by Itay080** [lassir/bcrypt-samp#6] opened 2017-07-01 09:21 UTC
I am generating my hashes using my UCP in ASP.NET which uses Bcrypt.Net for C#, when I check if the hash needs rehashing in Bcrypt-samp it always says that the hash is in need for rehashing.
The cost in both Bcrypt.net and Bcrypt-samp are similar.

**Comment by lassir** [comment] 2021-02-19 17:13
Closing as the issue is rather old.

**Closed by lassir** 2021-02-19 17:13 UTC
